[GLOBAL]
pants_version = "2.14.0rc5"
backend_packages = [
  "pants.backend.experimental.python",
  "pants.backend.experimental.python.lint.autoflake",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]


[anonymous-telemetry]
enabled = true
repo_id = "CEDB33C9-50CB-43A5-9E81-68741442ABB4"


[mypy]
args = "--namespace-packages --explicit-package-bases"


[python]
interpreter_constraints = [">=3.8, <3.10"]
enable_resolves = true


[python.resolves]
python-default = "3rdparty/requirements.lock"
